# Generated by Django 5.2.5 on 2025-08-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailsendcount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usertype',
            table=None,
        ),
    ]
