# Generated by Django 5.1.3 on 2024-12-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='is_current',
        ),
    ]
