# Generated by Django 5.1.3 on 2024-12-11 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0002_remove_usertype_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_auth.usertype'),
        ),
    ]
