# Generated by Django 5.2.5 on 2025-08-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0002_alter_emailsendcount_table_alter_user_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendcount',
            name='email_count_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='user_type_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
