# Generated by Django 5.2.5 on 2025-08-19 13:12

from django.db import migrations, models
import uuid

def populate_uuid_fields(apps, schema_editor):

    UserType = apps.get_model("oyiche_auth", "UserType")
    for obj in UserType.objects.all():
        obj.user_type_id = uuid.uuid4()
        obj.save(update_fields=["user_type_id"])

    EmailSendCount = apps.get_model("oyiche_auth", "EmailSendCount")
    for obj in EmailSendCount.objects.all():
        obj.email_count_id = uuid.uuid4()
        obj.save(update_fields=["email_count_id"])

class Migration(migrations.Migration):

    atomic = True

    dependencies = [
        ('oyiche_auth', '0003_emailsendcount_email_count_id_usertype_user_type_id'),
    ]

    operations = [
        migrations.RunPython(populate_uuid_fields),
    ]
