# Generated by Django 5.2.5 on 2025-08-19 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0004_auto_20250819_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendcount',
            name='email_count_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
