# Generated by Django 5.2.5 on 2025-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0005_alter_emailsendcount_email_count_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
