# Generated by Django 5.2.5 on 2025-08-27 15:01

from django.db import migrations

def populate_foreign_keys_with_uuid(apps, schema_editor):

    User = apps.get_model("oyiche_auth", "User")
    for obj in User.objects.all():

        obj.userType_uuid = obj.userType.user_type_id

        obj.save(update_fields=["userType_uuid"])

class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ('oyiche_auth', '0006_user_usertype_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_foreign_keys_with_uuid),
    ]
