# Generated by Django 5.2.5 on 2025-08-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0007_auto_20250827_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
    ]
