# Generated by Django 5.2.5 on 2025-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0008_remove_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendcount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
