# Generated by Django 5.2.5 on 2025-08-19 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0009_alter_emailsendcount_id_alter_usertype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsendcount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailsendcount',
            name='email_count_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
