# Generated by Django 5.2.5 on 2025-08-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0010_remove_emailsendcount_id_remove_usertype_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_auth.usertype'),
        ),
    ]
