# Generated by Django 5.2.5 on 2025-08-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_auth', '0011_alter_user_usertype_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userType_uuid',
            new_name='userType',
        ),
    ]
