# Generated by Django 5.1.4 on 2025-01-06 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20, unique=True)),
                ('session_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Session',
                'db_table': 'Academic Session',
            },
        ),
        migrations.CreateModel(
            name='AcademicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, unique=True)),
                ('status_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Status',
                'db_table': 'Academic Status',
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20, unique=True)),
                ('term_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Term',
                'db_table': 'Academic Term',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gender',
                'db_table': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=20, unique=True)),
                ('category_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'School Categories',
                'db_table': 'School Category',
            },
        ),
        migrations.CreateModel(
            name='SchoolClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'School Classes',
                'db_table': 'School Classes',
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_title', models.CharField(max_length=20, unique=True)),
                ('school_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'School Type',
                'db_table': 'School Type',
            },
        ),
        migrations.CreateModel(
            name='ClassSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_class', to='oyiche_schMGT.schoolclasses')),
            ],
            options={
                'verbose_name_plural': 'Class Subjects',
                'db_table': 'Class Subjects',
            },
        ),
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('sch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(db_index=True, max_length=500)),
                ('school_username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('school_email', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='email address')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='uploads/logos/')),
                ('school_address', models.CharField(db_index=True, max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('principal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolcategory')),
                ('school_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schooltype')),
            ],
            options={
                'verbose_name_plural': 'School Information',
                'db_table': 'School Information',
            },
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_class', to='oyiche_schMGT.schoolinformation'),
        ),
        migrations.CreateModel(
            name='SchoolAdminInformation',
            fields=[
                ('sch_admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name_plural': 'School Admin Information',
                'db_table': 'School Admin Information',
            },
        ),
        migrations.CreateModel(
            name='SchoolAcademicInformation',
            fields=[
                ('academic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_current', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_session', to='oyiche_schMGT.academicsession')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_term', to='oyiche_schMGT.academicterm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_infos', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name_plural': 'School Academic Information',
                'db_table': 'School Academic Information',
            },
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(db_index=True, max_length=500)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.gender')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolinformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Information',
                'db_table': 'Student Information',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('academic_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.academicstatus')),
                ('promoted_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_class', to='oyiche_schMGT.schoolclasses')),
                ('school_academic_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolacademicinformation')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollment_class', to='oyiche_schMGT.schoolclasses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_information', to='oyiche_schMGT.studentinformation')),
            ],
            options={
                'verbose_name_plural': 'Student Enrollments',
                'db_table': 'Student Enrollment',
            },
        ),
    ]
