# Generated by Django 5.1.4 on 2024-12-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.gender'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolinformation'),
        ),
    ]
