# Generated by Django 5.1.5 on 2025-04-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('term_description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'General Academic Term',
                'db_table': 'General Academic Term',
            },
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_academic_session', to='oyiche_schMGT.academicsession'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
