# Generated by Django 5.1.4 on 2024-12-20 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0002_alter_studentinformation_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolacademicinformation',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_session', to='oyiche_schMGT.academicsession'),
        ),
        migrations.AlterField(
            model_name='schoolacademicinformation',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_term', to='oyiche_schMGT.academicterm'),
        ),
        migrations.AlterField(
            model_name='schoolacademicinformation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_infos', to='oyiche_schMGT.schoolinformation'),
        ),
    ]
