# Generated by Django 5.1.5 on 2025-04-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0002_generalacademicterm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
