# Generated by Django 5.1.4 on 2025-01-06 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0002_rename_school_schoolclasses_school_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolcategory'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schooltype'),
        ),
    ]
