# Generated by Django 5.1.4 on 2024-12-20 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0003_alter_schoolacademicinformation_academic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_information', to='oyiche_schMGT.studentinformation'),
        ),
    ]
