# Generated by Django 5.1.4 on 2025-01-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0003_alter_schoolinformation_school_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='school_info',
            field=models.ForeignKey(default='cc9ff295d8a74504bbcbc5e88a13cbbe', on_delete=django.db.models.deletion.CASCADE, related_name='school_info', to='oyiche_schMGT.schoolinformation'),
            preserve_default=False,
        ),
    ]
