# Generated by Django 5.1.5 on 2025-04-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0003_academicsession_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
