# Generated by Django 5.2.5 on 2025-08-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0004_studentenrollment_has_paid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academicsession',
            table=None,
        ),
        migrations.AlterModelTable(
            name='academicstatus',
            table=None,
        ),
        migrations.AlterModelTable(
            name='academicterm',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gender',
            table=None,
        ),
        migrations.AlterModelTable(
            name='generalacademicterm',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schooladmininformation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolclasses',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolclasssubjects',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolgrades',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolinformation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolremark',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolsubject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schooltype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentenrollment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentinformation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentperformance',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentscores',
            table=None,
        ),
    ]
