# Generated by Django 5.2.5 on 2025-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0005_alter_academicsession_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='academic_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicstatus',
            name='academic_status_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='academic_term_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalacademicterm',
            name='general_academic_term_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolcategory',
            name='sch_category_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='class_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolclasssubjects',
            name='sch_class_subject_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolgrades',
            name='sch_grade_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolremark',
            name='sch_remark_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='sch_subject_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooltype',
            name='sch_type_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='performance_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentscores',
            name='student_score_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
