# Generated by Django 5.1.4 on 2025-01-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0005_remove_studentenrollment_school_academic_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclasses',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='schoolclasses',
            constraint=models.UniqueConstraint(fields=('school_info', 'class_name'), name='unique_class_per_school'),
        ),
    ]
