# Generated by Django 5.1.4 on 2025-01-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0006_alter_schoolclasses_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclasses',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
