# Generated by Django 5.1.4 on 2025-01-08 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0007_alter_schoolclasses_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subject', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name_plural': 'School Subject',
                'db_table': 'School Subject',
            },
        ),
        migrations.CreateModel(
            name='SchoolClassSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_class', to='oyiche_schMGT.schoolclasses')),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subject', to='oyiche_schMGT.schoolsubject')),
            ],
            options={
                'verbose_name_plural': 'School Class Subjects',
                'db_table': 'School Class Subjects',
            },
        ),
        migrations.DeleteModel(
            name='ClassSubjects',
        ),
        migrations.AddConstraint(
            model_name='schoolsubject',
            constraint=models.UniqueConstraint(fields=('school_info', 'subject_name'), name='unique_subject_per_school'),
        ),
    ]
