# Generated by Django 5.2.5 on 2025-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0008_alter_academicsession_academic_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmininformation',
            name='gender_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolclasssubjects',
            name='school_class_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolclasssubjects',
            name='school_subject_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolinformation',
            name='school_category_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolinformation',
            name='school_type_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_session_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_status_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_term_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='promoted_class_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student_class_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='gender_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='school_remark_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentscores',
            name='grade_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentscores',
            name='session_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentscores',
            name='subject_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentscores',
            name='term_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
