# Generated by Django 5.1.4 on 2025-01-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0008_schoolsubject_schoolclasssubjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclasssubjects',
            name='school_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_class_subject', to='oyiche_schMGT.schoolinformation'),
        ),
    ]
