# Generated by Django 5.1.4 on 2025-01-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0009_schoolclasssubjects_school_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_letter', models.CharField(max_length=1, unique=True)),
                ('min_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('grade_description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_grades', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name_plural': 'School Grades',
                'db_table': 'School Grades',
            },
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.IntegerField(default=0)),
                ('term_position', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('current_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollment', to='oyiche_schMGT.studentenrollment')),
                ('school_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_student_performance', to='oyiche_schMGT.schoolinformation')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_performance', to='oyiche_schMGT.studentinformation')),
            ],
            options={
                'verbose_name_plural': 'Student Performance',
                'db_table': 'Student Performance',
            },
        ),
        migrations.CreateModel(
            name='StudentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ca', models.IntegerField(default=0)),
                ('second_ca', models.IntegerField(default=0)),
                ('third_ca', models.IntegerField(default=0)),
                ('excam', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_grade_scores', to='oyiche_schMGT.schoolgrades')),
                ('school_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_student_scores', to='oyiche_schMGT.schoolinformation')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_session_scores', to='oyiche_schMGT.academicsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='oyiche_schMGT.studentinformation')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_scores', to='oyiche_schMGT.schoolclasssubjects')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_term_scores', to='oyiche_schMGT.academicterm')),
            ],
            options={
                'verbose_name_plural': 'Student Scores',
                'db_table': 'Student Scores',
            },
        ),
    ]
