# Generated by Django 5.2.5 on 2025-08-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0010_auto_20250819_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooladmininformation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='schoolclasssubjects',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='schoolclasssubjects',
            name='school_subject',
        ),
        migrations.RemoveField(
            model_name='schoolinformation',
            name='school_category',
        ),
        migrations.RemoveField(
            model_name='schoolinformation',
            name='school_type',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='academic_status',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='academic_term',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='promoted_class',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='school_remark',
        ),
        migrations.RemoveField(
            model_name='studentscores',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentscores',
            name='session',
        ),
        migrations.RemoveField(
            model_name='studentscores',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentscores',
            name='term',
        ),
    ]
