# Generated by Django 5.1.4 on 2025-01-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0011_alter_schoolgrades_grade_letter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentscores',
            old_name='excam',
            new_name='exam',
        ),
    ]
