# Generated by Django 5.1.4 on 2025-01-15 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0012_rename_excam_studentscores_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='school_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_information', to='oyiche_schMGT.schoolinformation'),
        ),
    ]
