# Generated by Django 5.2.5 on 2025-08-27 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0012_alter_academicsession_id_alter_academicstatus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='academicstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='academicterm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='id',
        ),
        migrations.RemoveField(
            model_name='generalacademicterm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolclasses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolclasssubjects',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolgrades',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolremark',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolsubject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schooltype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentscores',
            name='id',
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='academic_session_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='academicstatus',
            name='academic_status_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='academic_term_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='generalacademicterm',
            name='general_academic_term_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolcategory',
            name='sch_category_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolclasses',
            name='class_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolclasssubjects',
            name='sch_class_subject_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolgrades',
            name='sch_grade_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolremark',
            name='sch_remark_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolsubject',
            name='sch_subject_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schooltype',
            name='sch_type_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='performance_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentscores',
            name='student_score_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
