# Generated by Django 5.2.5 on 2025-08-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0013_remove_academicsession_id_remove_academicstatus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladmininformation',
            name='gender_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.gender'),
        ),
        migrations.AlterField(
            model_name='schoolclasssubjects',
            name='school_class_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_class', to='oyiche_schMGT.schoolclasses'),
        ),
        migrations.AlterField(
            model_name='schoolclasssubjects',
            name='school_subject_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject', to='oyiche_schMGT.schoolsubject'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_category_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolcategory'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_type_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schooltype'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='academic_session_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_academic_session', to='oyiche_schMGT.academicsession'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='academic_status_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.academicstatus'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='academic_term_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_term', to='oyiche_schMGT.academicterm'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='promoted_class_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_class', to='oyiche_schMGT.schoolclasses'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student_class_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollment_class', to='oyiche_schMGT.schoolclasses'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='gender_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.gender'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='school_remark_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_performance_remark', to='oyiche_schMGT.schoolremark'),
        ),
        migrations.AlterField(
            model_name='studentscores',
            name='grade_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_grade_scores', to='oyiche_schMGT.schoolgrades'),
        ),
        migrations.AlterField(
            model_name='studentscores',
            name='session_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_session_scores', to='oyiche_schMGT.academicsession'),
        ),
        migrations.AlterField(
            model_name='studentscores',
            name='subject_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_scores', to='oyiche_schMGT.schoolclasssubjects'),
        ),
        migrations.AlterField(
            model_name='studentscores',
            name='term_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_term_scores', to='oyiche_schMGT.academicterm'),
        ),
    ]
