# Generated by Django 5.1.4 on 2025-01-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0013_studentenrollment_school_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='school_info',
        ),
    ]
