# Generated by Django 5.2.5 on 2025-08-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0014_alter_schooladmininformation_gender_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooladmininformation',
            old_name='gender_uuid',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='schoolclasssubjects',
            old_name='school_class_uuid',
            new_name='school_class',
        ),
        migrations.RenameField(
            model_name='schoolclasssubjects',
            old_name='school_subject_uuid',
            new_name='school_subject',
        ),
        migrations.RenameField(
            model_name='schoolinformation',
            old_name='school_category_uuid',
            new_name='school_category',
        ),
        migrations.RenameField(
            model_name='schoolinformation',
            old_name='school_type_uuid',
            new_name='school_type',
        ),
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='academic_session_uuid',
            new_name='academic_session',
        ),
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='academic_status_uuid',
            new_name='academic_status',
        ),
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='academic_term_uuid',
            new_name='academic_term',
        ),
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='promoted_class_uuid',
            new_name='promoted_class',
        ),
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='student_class_uuid',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='studentinformation',
            old_name='gender_uuid',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='studentperformance',
            old_name='school_remark_uuid',
            new_name='school_remark',
        ),
        migrations.RenameField(
            model_name='studentscores',
            old_name='grade_uuid',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='studentscores',
            old_name='session_uuid',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='studentscores',
            old_name='subject_uuid',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='studentscores',
            old_name='term_uuid',
            new_name='term',
        ),
    ]
