# Generated by Django 5.1.4 on 2025-01-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0015_remove_studentperformance_average_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='student_total',
            field=models.FloatField(default=0),
        ),
    ]
