# Generated by Django 5.1.4 on 2025-01-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0016_studentperformance_student_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='lowest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentscores',
            name='average',
            field=models.FloatField(default=0),
        ),
    ]
