# Generated by Django 5.1.4 on 2025-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0017_studentperformance_highest_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentperformance',
            name='highest_score',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='lowest_score',
        ),
        migrations.AddField(
            model_name='studentscores',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentscores',
            name='lowest_score',
            field=models.IntegerField(default=0),
        ),
    ]
