# Generated by Django 5.1.4 on 2025-01-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0018_remove_studentperformance_highest_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscores',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
