# Generated by Django 5.1.4 on 2025-01-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0019_studentscores_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentperformance',
            name='student_total',
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='total_marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='total_subject',
            field=models.IntegerField(default=0),
        ),
    ]
