# Generated by Django 5.1.4 on 2025-01-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0020_remove_studentperformance_student_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='term_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
