# Generated by Django 5.1.5 on 2025-01-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0021_alter_studentperformance_term_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstatus',
            name='school_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_academic_status', to='oyiche_schMGT.schoolinformation'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='academicstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='term',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('school_info', 'session'), name='unique_session_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicstatus',
            constraint=models.UniqueConstraint(fields=('school_info', 'status'), name='unique_status_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(fields=('school_info', 'term'), name='unique_term_per_school'),
        ),
    ]
