# Generated by Django 5.1.5 on 2025-01-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0022_academicstatus_school_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_address',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolcategory'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schooltype'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_username',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
