# Generated by Django 5.1.5 on 2025-02-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0025_alter_schoolinformation_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformation',
            name='school_updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
