# Generated by Django 5.1.5 on 2025-02-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0026_schoolinformation_school_updated'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicstatus',
            name='unique_status_per_school',
        ),
        migrations.RemoveField(
            model_name='academicstatus',
            name='school_info',
        ),
    ]
