# Generated by Django 5.1.5 on 2025-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0028_alter_schooltype_school_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltype',
            name='school_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
