# Generated by Django 5.1.5 on 2025-02-25 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0029_alter_schooltype_school_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='oyiche_schMGT.schoolinformation'),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SchoolPrincipalRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_average', models.FloatField(default=0)),
                ('max_average', models.FloatField(default=100)),
                ('principal_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_principal_remark', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name_plural': 'School Principal Remarks',
                'db_table': 'School Principal Remark',
            },
        ),
        migrations.CreateModel(
            name='SchoolTeacherRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_average', models.FloatField(default=0)),
                ('max_average', models.FloatField(default=100)),
                ('teacher_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_teacher_remark', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name_plural': 'School Teacher Remarks',
                'db_table': 'School Teacher Remark',
            },
        ),
    ]
