# Generated by Django 5.1.5 on 2025-02-26 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0030_alter_studentinformation_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolteacherremark',
            name='school_info',
        ),
        migrations.CreateModel(
            name='SchoolRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_average', models.FloatField(default=0)),
                ('max_average', models.FloatField(default=100)),
                ('teacher_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('principal_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_teacher_remark', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name_plural': 'School Remarks',
                'db_table': 'School Remark',
            },
        ),
        migrations.DeleteModel(
            name='SchoolPrincipalRemark',
        ),
        migrations.DeleteModel(
            name='SchoolTeacherRemark',
        ),
    ]
