# Generated by Django 5.1.5 on 2025-03-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_schMGT', '0031_remove_schoolteacherremark_school_info_schoolremark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='school_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_performance_remark', to='oyiche_schMGT.schoolremark'),
        ),
    ]
