# Generated by Django 5.1.5 on 2025-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
    ]
