# Generated by Django 5.2.5 on 2025-08-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table=None,
        ),
    ]
