# Generated by Django 5.2.5 on 2025-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_basic', '0002_alter_contactus_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
