# Generated by Django 5.2.5 on 2025-08-19 13:10

from django.db import migrations, models
import uuid

def populate_uuid_fields(apps, schema_editor):

    ContactUs = apps.get_model("oyiche_basic", "ContactUs")
    for obj in ContactUs.objects.all():
        obj.contact_id = uuid.uuid4()
        obj.save(update_fields=["contact_id"])

class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ('oyiche_basic', '0003_contactus_contact_id'),
    ]

    operations = [
        migrations.RunPython(populate_uuid_fields),
    ]
