# Generated by Django 5.2.5 on 2025-08-19 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_basic', '0004_auto_20250819_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
