# Generated by Django 5.2.5 on 2025-08-27 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_basic', '0006_alter_contactus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='id',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
