# Generated by Django 5.1.4 on 2024-12-19 03:57

import django.db.models.deletion
import oyiche_files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oyiche_schMGT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'File Template Type',
                'db_table': 'File Template Type',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'File Types',
                'db_table': 'File Types',
            },
        ),
        migrations.CreateModel(
            name='FilesTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/templates')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('template_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_files.filetemplatetype')),
            ],
            options={
                'verbose_name_plural': 'Files Templates',
                'db_table': 'Files Templates',
            },
        ),
        migrations.CreateModel(
            name='FilesManager',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=oyiche_files.models.path_and_rename)),
                ('processing_status', models.CharField(default='File has not been processed Yet!', max_length=200)),
                ('used', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolinformation')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.studentclass')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oyiche_files.filetype')),
            ],
            options={
                'verbose_name_plural': 'Files Manager',
                'db_table': 'Files Manager',
            },
        ),
    ]
