# Generated by Django 5.1.4 on 2025-01-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesmanager',
            old_name='student_class',
            new_name='class_name',
        ),
    ]
