# Generated by Django 5.2.5 on 2025-08-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filesmanager',
            table=None,
        ),
        migrations.AlterModelTable(
            name='filestemplates',
            table=None,
        ),
        migrations.AlterModelTable(
            name='filetemplatetype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='filetype',
            table=None,
        ),
    ]
