# Generated by Django 5.2.5 on 2025-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0002_alter_filesmanager_table_alter_filestemplates_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestemplates',
            name='file_template_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetemplatetype',
            name='file_template_type_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetype',
            name='file_type_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
