# Generated by Django 5.2.5 on 2025-08-27 13:01

from django.db import migrations, models
import uuid

def populate_uuid_fields(apps, schema_editor):

    FileType = apps.get_model("oyiche_files", "FileType")
    for obj in FileType.objects.all():
        obj.file_type_id = uuid.uuid4()
        obj.save(update_fields=["file_type_id"])

    FileTemplateType = apps.get_model("oyiche_files", "FileTemplateType")
    for obj in FileTemplateType.objects.all():
        obj.file_template_type_id = uuid.uuid4()
        obj.save(update_fields=["file_template_type_id"])

    FilesTemplates = apps.get_model("oyiche_files", "FilesTemplates")
    for obj in FilesTemplates.objects.all():
        obj.file_template_id = uuid.uuid4()
        obj.save(update_fields=["file_template_id"])

class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ('oyiche_files', '0003_filestemplates_file_template_id_and_more'),

    ]

    operations = [
        migrations.RunPython(populate_uuid_fields),
    ]
