# Generated by Django 5.2.5 on 2025-08-27 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0004_auto_20250827_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestemplates',
            name='file_template_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='filetemplatetype',
            name='file_template_type_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file_type_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
