# Generated by Django 5.2.5 on 2025-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0005_alter_filestemplates_file_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmanager',
            name='class_name_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesmanager',
            name='file_type_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filestemplates',
            name='template_type_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
