# Generated by Django 5.2.5 on 2025-08-27 15:05

from django.db import migrations

def populate_foreign_keys_with_uuid(apps, schema_editor):

    FilesManager = apps.get_model("oyiche_files", "FilesManager")
    for obj in FilesManager.objects.all():

        obj.class_name_uuid = obj.class_name.class_id
        obj.file_type_uuid = obj.file_type.file_type_id

        obj.save(update_fields=["class_name_uuid", "file_type_uuid"])

    FilesTemplates = apps.get_model("oyiche_files", "FilesTemplates")
    for obj in FilesTemplates.objects.all():

        obj.template_type_uuid = obj.template_type.file_template_type_id

        obj.save(update_fields=["template_type_uuid"])

class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ('oyiche_files', '0006_filesmanager_class_name_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_foreign_keys_with_uuid),
    ]
