# Generated by Django 5.2.5 on 2025-08-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0007_auto_20250819_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesmanager',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='filesmanager',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='filestemplates',
            name='template_type',
        ),
    ]
