# Generated by Django 5.2.5 on 2025-08-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0008_remove_filesmanager_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestemplates',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filetemplatetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
