# Generated by Django 5.2.5 on 2025-08-19 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0009_alter_filestemplates_id_alter_filetemplatetype_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestemplates',
            name='id',
        ),
        migrations.RemoveField(
            model_name='filetemplatetype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='id',
        ),
        migrations.AlterField(
            model_name='filestemplates',
            name='file_template_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='filetemplatetype',
            name='file_template_type_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file_type_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
