# Generated by Django 5.2.5 on 2025-08-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0010_remove_filestemplates_id_remove_filetemplatetype_id_and_more'),
        ('oyiche_schMGT', '0014_alter_schooladmininformation_gender_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmanager',
            name='class_name_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_schMGT.schoolclasses'),
        ),
        migrations.AlterField(
            model_name='filesmanager',
            name='file_type_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_files.filetype'),
        ),
        migrations.AlterField(
            model_name='filestemplates',
            name='template_type_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oyiche_files.filetemplatetype'),
        ),
    ]
