# Generated by Django 5.2.5 on 2025-08-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_files', '0011_alter_filesmanager_class_name_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesmanager',
            old_name='class_name_uuid',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='filesmanager',
            old_name='file_type_uuid',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='filestemplates',
            old_name='template_type_uuid',
            new_name='template_type',
        ),
    ]
