# Generated by Django 5.1.5 on 2025-05-12 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oyiche_schMGT', '0004_studentenrollment_has_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_incentive', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Product Cost',
                'verbose_name_plural': 'Product Costs',
                'db_table': 'Product Cost',
            },
        ),
        migrations.CreateModel(
            name='SchoolPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_purchased', models.IntegerField(default=1)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_session', to='oyiche_schMGT.academicsession')),
                ('academic_term', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_academic_term', to='oyiche_schMGT.academicterm')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_payment_info', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name': 'School Payment History',
                'verbose_name_plural': 'School Payment History',
                'db_table': 'payment_history',
            },
        ),
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_unit', models.IntegerField(default=0)),
                ('total_unit', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_unit_info', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name': 'School Unit',
                'verbose_name_plural': 'School Units',
                'db_table': 'School Unit',
            },
        ),
        migrations.CreateModel(
            name='UnitUsedByTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_used', models.IntegerField(default=0)),
                ('academic_session', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='school_unit_session', to='oyiche_schMGT.academicsession')),
                ('academic_term', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='school_unit_term', to='oyiche_schMGT.academicterm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_unit_used', to='oyiche_schMGT.schoolinformation')),
            ],
            options={
                'verbose_name': 'Unit Used By Term',
                'verbose_name_plural': 'Unit Used By Terms',
                'db_table': 'Term_Unit',
            },
        ),
    ]
