# Generated by Django 5.1.5 on 2025-05-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpaymenthistory',
            name='reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
