# Generated by Django 5.2.5 on 2025-08-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcost',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolpaymenthistory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='schoolunit',
            table=None,
        ),
        migrations.AlterModelTable(
            name='unitusedbyterm',
            table=None,
        ),
    ]
