# Generated by Django 5.2.5 on 2025-08-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0002_alter_productcost_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcost',
            name='product_cost_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolpaymenthistory',
            name='sch_payment_history_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolunit',
            name='sch_unit_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitusedbyterm',
            name='unit_used_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
