# Generated by Django 5.1.5 on 2025-05-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0002_schoolpaymenthistory_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolpaymenthistory',
            name='trx_reference',
        ),
    ]
