# Generated by Django 5.2.5 on 2025-08-19 13:01

from django.db import migrations, models
import uuid

def populate_uuid_fields(apps, schema_editor):

    ProductCost = apps.get_model("oyiche_payment", "ProductCost")
    for obj in ProductCost.objects.all():
        obj.product_cost_id = uuid.uuid4()
        obj.save(update_fields=["product_cost_id"])

    SchoolUnit = apps.get_model("oyiche_payment", "SchoolUnit")
    for obj in SchoolUnit.objects.all():
        obj.sch_unit_id = uuid.uuid4()
        obj.save(update_fields=["sch_unit_id"])

    UnitUsedByTerm = apps.get_model("oyiche_payment", "UnitUsedByTerm")
    for obj in UnitUsedByTerm.objects.all():
        obj.unit_used_id = uuid.uuid4()
        obj.save(update_fields=["unit_used_id"])

    SchoolPaymentHistory = apps.get_model("oyiche_payment", "SchoolPaymentHistory")
    for obj in SchoolPaymentHistory.objects.all():
        obj.sch_payment_history_id = uuid.uuid4()
        obj.save(update_fields=["sch_payment_history_id"])

class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0003_productcost_product_cost_id_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_uuid_fields),
    ]
