# Generated by Django 5.2.5 on 2025-08-27 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0004_auto_20250827_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcost',
            name='product_cost_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolpaymenthistory',
            name='sch_payment_history_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolunit',
            name='sch_unit_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='unitusedbyterm',
            name='unit_used_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
