# Generated by Django 5.2.5 on 2025-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0005_alter_productcost_product_cost_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpaymenthistory',
            name='academic_session_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolpaymenthistory',
            name='academic_term_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitusedbyterm',
            name='academic_session_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitusedbyterm',
            name='academic_term_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
