# Generated by Django 5.2.5 on 2025-08-19 15:26

from django.db import migrations

def populate_foreign_keys_with_uuid(apps, schema_editor):

    UnitUsedByTerm = apps.get_model("oyiche_payment", "UnitUsedByTerm")
    for obj in UnitUsedByTerm.objects.all():

        obj.academic_session_uuid = obj.academic_session.academic_session_id
        obj.academic_term_uuid = obj.academic_term.academic_term_id

        obj.save(update_fields=["academic_session_uuid", "academic_term_uuid"])

    SchoolPaymentHistory = apps.get_model("oyiche_payment", "SchoolPaymentHistory")
    for obj in SchoolPaymentHistory.objects.all():

        obj.academic_session_uuid = obj.academic_session.academic_session_id
        obj.academic_term_uuid = obj.academic_term.academic_term_id

        obj.save(update_fields=["academic_session_uuid", "academic_term_uuid"])

class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ('oyiche_payment', '0006_schoolpaymenthistory_academic_session_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_foreign_keys_with_uuid),
    ]
