# Generated by Django 5.2.5 on 2025-08-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0007_auto_20250819_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolpaymenthistory',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='schoolpaymenthistory',
            name='academic_term',
        ),
        migrations.RemoveField(
            model_name='unitusedbyterm',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='unitusedbyterm',
            name='academic_term',
        ),
    ]
