# Generated by Django 5.2.5 on 2025-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0008_remove_schoolpaymenthistory_academic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoolpaymenthistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoolunit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitusedbyterm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
