# Generated by Django 5.2.5 on 2025-08-27 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0009_alter_productcost_id_alter_schoolpaymenthistory_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolpaymenthistory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schoolunit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unitusedbyterm',
            name='id',
        ),
        migrations.AlterField(
            model_name='productcost',
            name='product_cost_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolpaymenthistory',
            name='sch_payment_history_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolunit',
            name='sch_unit_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unitusedbyterm',
            name='unit_used_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
