# Generated by Django 5.2.5 on 2025-08-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0010_remove_productcost_id_remove_schoolpaymenthistory_id_and_more'),
        ('oyiche_schMGT', '0014_alter_schooladmininformation_gender_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpaymenthistory',
            name='academic_session_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_session', to='oyiche_schMGT.academicsession'),
        ),
        migrations.AlterField(
            model_name='schoolpaymenthistory',
            name='academic_term_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_academic_term', to='oyiche_schMGT.academicterm'),
        ),
        migrations.AlterField(
            model_name='unitusedbyterm',
            name='academic_session_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_unit_session', to='oyiche_schMGT.academicsession'),
        ),
        migrations.AlterField(
            model_name='unitusedbyterm',
            name='academic_term_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_unit_term', to='oyiche_schMGT.academicterm'),
        ),
    ]
