# Generated by Django 5.2.5 on 2025-08-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyiche_payment', '0011_alter_schoolpaymenthistory_academic_session_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolpaymenthistory',
            old_name='academic_session_uuid',
            new_name='academic_session',
        ),
        migrations.RenameField(
            model_name='schoolpaymenthistory',
            old_name='academic_term_uuid',
            new_name='academic_term',
        ),
        migrations.RenameField(
            model_name='unitusedbyterm',
            old_name='academic_session_uuid',
            new_name='academic_session',
        ),
        migrations.RenameField(
            model_name='unitusedbyterm',
            old_name='academic_term_uuid',
            new_name='academic_term',
        ),
    ]
